import {body} from "express-validator";

export const codeValidation = body('code')
    .exists()
    .withMessage('Registration confirmation code is required')
    .isString()
    .withMessage('Registration confirmation code must be string')
    .trim()
    .isLength({min: 1})
    .withMessage('Wrong code length')

export const emailValidation = body('email')
    .exists()
    .withMessage('Email is required')
    .isString()
    .withMessage('Email must be string')
    .trim()
    .isLength({ min: 1})
    .isEmail()
    .withMessage('Email must be a valid email address')